version: '3.7'

networks:
  custom:
    name: custom
    driver: bridge

services:
  certbot:
    image: crblab/certbot:latest
    container_name: certbot
    networks:
      - custom
    volumes: 
      - ~/docker/certbot:/certs
    env_file:
      - deploy.env