version: '3.7'

networks:
  custom:
    name: custom
    driver: bridge

services:
  certbot:
    image: crblab/certbot:latest
    container_name: certbot
    networks:
      - custom
    volumes: 
      - ~/dockerdata/certbot/certs:/certs
      - ~/dockerdata/certbot/live:/etc/letsencrypt/live
    env_file:
      - deploy.env