version: '3.7'

networks:
  custom:
    name: custom
    driver: bridge
  default:
    external:
      name: custom

services:
  certbot:
    image: hieupth/certbot:latest
    container_name: certbot
    networks:
      - custom
    volumes: 
      - ~/docker/volumes/certbot:/certs
    env_file:
      - .env
